import type { items } from "./items";

/** States supported by the distributed source. The live preview shows a useful subset. */
export const itemStates: Record<keyof typeof items, string> = {
"compare": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"compliance": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"contact": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"cta": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"download": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"experience": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"faq": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",
"form": "Application-owned content and destinations; submission callbacks do not bundle a backend. The docs demonstrate local interactions.",

"about": "Content and links are supplied by your application. Examples use local demonstration data.",
"awards": "Content and links are supplied by your application. Examples use local demonstration data.",
"blog": "Content and links are supplied by your application. Examples use local demonstration data.",
"blog-post": "Content and links are supplied by your application. Examples use local demonstration data.",
"careers": "Content and links are supplied by your application. Examples use local demonstration data.",
"case-studies": "Content and links are supplied by your application. Examples use local demonstration data.",
"case-study": "Content and links are supplied by your application. Examples use local demonstration data.",
"changelog": "Content and links are supplied by your application. Examples use local demonstration data.",
"code-example": "Content and links are supplied by your application. Examples use local demonstration data.",
"community": "Content and links are supplied by your application. Examples use local demonstration data.",

  "codebase": "Files and file tree are supplied by the application. Folders expand with arrow keys; file selection and clipboard copy remain local.",
  "collaborative-canvas": "Positions are 0\u2013100 percent. Drag objects or use arrows; Shift moves by ten percent. Your app supplies presence and persistence; this example uses a local simulation.",
  "roadmap": "Dates are local calendar dates. Filtered edits preserve other tasks. Changes are callbacks; no backend is bundled. Native visible actions provide alternatives to context menus and drag.",

  "sidebar": "Controlled state; see Examples.",
  "message": "Controlled state; see Examples.",
  "message-scroller": "Controlled state; see Examples.",
  "questionnaire": "Controlled state; see Examples.",

  "carousel": "Controlled interaction; see Examples.",
  "context-menu": "Controlled interaction; see Examples.",
  "drawer": "Controlled interaction; see Examples.",
  "menubar": "Controlled interaction; see Examples.",
  "navigation-menu": "Controlled interaction; see Examples.",
  "resizable": "Controlled interaction; see Examples.",
  "scroll-area": "Controlled interaction; see Examples.",

  "attachment": "Static content and app-controlled interaction; see Usage and Examples.",
  "bubble": "Static content and app-controlled interaction; see Usage and Examples.",
  "direction": "Static content and app-controlled interaction; see Usage and Examples.",
  "input-otp": "Static content and app-controlled interaction; see Usage and Examples.",
  "item": "Static content and app-controlled interaction; see Usage and Examples.",
  "marker": "Static content and app-controlled interaction; see Usage and Examples.",

  "date-picker": "empty/selected/open/disabled/bounded/range-in-progress/complete. unavailable 날짜를 포함하는 range는 거절하고 status로 안내합니다.",
  "data-table": "default/sorted/filtered/empty/selected/hidden columns/first-last page. 필터 변경 시 첫 페이지로 돌아갑니다.",
  "hover-card": "closed/open. portal과 viewport 충돌 배치를 Radix가 담당합니다.",
  "aspect-ratio": "정적 layout. 로딩 표시는 Skeleton을 별도로 조합합니다.",
  "kbd": "정적 설명. focus/disabled/loading이 없습니다.",
  "button-group": "부모 상태 없음. 자식 Button의 상태를 그대로 사용합니다.",
  "command": "검색 결과/empty/selected/disabled. Item disabled 상태는 data-disabled=true.",
  "pagination": "current/hover/focus/disabled. 이전/다음 한계는 consumer가 지정합니다.",
  "breadcrumb": "link hover/focus 및 current page. 로딩 동작은 없습니다.",
  "accordion": "open/closed/disabled. 닫히는 panel은 inert; reduced motion에서는 height transition을 제거합니다.",
  "toggle-group": "Selected/unselected, focused, disabled and single/multiple.",
  "toggle": "Pressed, unpressed, focused and disabled.",
  "input-group": "Empty, filled, focused, invalid, input disabled and independent button state.",
  "field": "Empty, filled, focused, invalid and disabled.",
  "radio-group": "Selected and unselected, focused, disabled.",
  "checkbox": "Unchecked, checked, mixed, focused, disabled, invalid.",
  "brand-action": "Animated or paused, loading/disabled, reduced motion and theme-defined brand colors.",
  "rotating-content": "Running, paused/resumed, static first item under reduced motion, inactive/offscreen suspension.",
  "media-reveal": "loading, ready, error and retry; hidden layers cannot be focused and reduced motion switches immediately.",
  "text-reveal": "Visible static HTML, one-shot entrance, Replay, and immediately readable reduced-motion content.",
  "brand-logo": "Full or icon-only at three sizes, app-owned name and mark, light/dark foreground. A surrounding link supplies hover and focus behavior; disabled and loading do not apply to a static identity.",
  button: "Default, hover, focus-visible, disabled and loading; loading prevents another activation.",
  input: "Empty, filled, focused, invalid and disabled; file inputs also show the selected file control.",
  select: "Closed, open, selected, focused and disabled; arrow keys move through options.",
  switch: "Unchecked, checked, focused and disabled; Space changes the value.",
  tabs: "Selected and unselected tabs, focused tab and horizontal or vertical orientation.",
  label: "A static native label; required or invalid feedback belongs to its associated input.",
  textarea: "Empty, filled, focused, invalid and disabled.",
  badge: "Default, secondary, outline and destructive presentations; labels carry meaning beyond color.",
  card: "Default and small density; optional leading image, action and footer.",
  separator: "Horizontal or vertical; decorative by default.",
  dialog: "Closed trigger, open modal, editable content, save/cancel and Escape focus return.",
  "dropdown-menu": "Closed/open menu, highlighted item, disabled item and destructive action.",
  popover: "Closed/open anchored content and focused controls; Escape restores focus.",
  sheet: "Closed/open side panel, focused content and Escape close.",
  tooltip: "Hidden, pointer hover and keyboard focus; content is supplementary.",
  chart: "Populated series and responsive layout; empty or loading data is an application decision.",
  skeleton: "Neutral by default, optional brand variant and reduced-motion stop.",
  "brand-gradient-text": "Static or animated short text; reduced motion stops repetition.",
  "status-notice": "Neutral, success, warning and destructive feedback with matching live-region semantics.",
  "reveal-content": "Before entry, visible after entry and immediately visible under reduced motion or without script.",
  collapsible: "Collapsed and expanded content with an announced trigger state.",
  progress: "Measured value with label; use a loading indicator when progress cannot be measured.",
  slider: "Single value or two-value range, focused thumb and keyboard adjustment.",
  toast: "Idle trigger, visible message and dismissal; the application chooses the result text.",
  avatar: "Loaded image or text fallback.",
  "alert-dialog": "Closed/open confirmation, explicit cancel or destructive confirmation and focus return.",
  "avatar-stack": "Named member avatars and an overflow count when more people are present.",
  cursor: "One or several app-positioned collaborator cursors with separate presence text.",
  calendar: "Schedule/date, single/range, selected/today, min/max and excluded dates, keyboard focus, incomplete range and rejected interior dates.",
  list: "Grouped rows before and after a keyboard-available move.",
  table: "Unsorted and sorted columns; dense rows scroll within the table on narrow screens.",
  "page-header": "Stacked actions on narrow screens and a row layout when space permits.",
  "state-panel": "Neutral, success, warning or destructive message; action and heading level are optional.",
  "product-page-intro": "Index, detail or task hierarchy with optional meta and aside action.",
  "resource-row-link": "Default, hover and focus-visible row; choose one link or one button target.",
  "page-skeleton": "Busy page structure with named loading status; motion stops under reduced motion.",
  "filter-toolbar": "Pressed/unpressed filters, search query, sort choice and an app-owned result count.",
  "empty-state": "First-use or zero-result message with an optional app-owned next action.",
  "form-section": "Stacked narrow layout or two-column layout with individually labelled fields.",
  "search-field": "Empty or populated query; the application supplies matching and no-result states.",
  "stat-card": "Value and optional detail; the application owns update and loading states.",
  "settings-section": "Grouped field values and an application-owned unsaved/saved result.",
  "bento-grid": "Responsive article spans and hover/focus-within emphasis; content remains app-owned.",
  gantt: "Scheduled item, moved item and resized duration with keyboard controls.",
  kanban: "Cards in multiple columns and a moved-card result with live status.",
  "code-block": "Selected sample or plain code, optional line numbers and copied feedback.",
  "contribution-graph": "Low/high activity, selected day and a scrollable annual grid on narrow screens.",
  sandbox: "Code, preview and optional console tabs; keyboard arrows select the view.",
  snippet: "Selected command tab and copied feedback for the active value.",
  choicebox: "Selected, unselected, focused and disabled choices.",
  combobox: "Closed, open, searching, empty, selected and disabled option.",
  dropzone: "Idle, dragging, accepted file, rejected file and disabled browse.",
  "mini-calendar": "Selected day and previous/next seven-day strip.",
  tags: "Selected tags, suggestion, added/removed tag, maximum count and disabled entry.",
  "image-crop": "Visible image, adjustable crop, reset and applied percentage bounds.",
  "image-zoom": "Thumbnail trigger and focused modal image; Escape closes it.",
  "credit-card": "Masked front and back, selected by the flip control.",
  ticker: "Positive or negative change and collapsed/expanded supplied details.",
  stories: "Thumbnail triggers, open viewer, current story, play/pause and reduced-motion stop.",
  reel: "Current video, play/pause, mute and previous/next; reduced motion starts paused.",
  "audio-player": "Loading, waveform-ready, native fallback, playback/error/retry, seek, volume/mute and speed.",
  "video-player": "Metadata loading, playing/paused/ended, buffering/error/retry, seek, volume/mute/speed, captions and fullscreen.",
  announcement: "Linked, static or dismissed compact update.",
  banner: "Prominent or subtle page message with optional dismissal.",
  typography: "Semantic element and visual type role are selected independently; text has no interactive state.",
  "color-picker": "Preset, saturation/brightness plane, hue, opacity and validated HEX entry.",
  comparison: "Before/after exposure from 0–100%, adjusted by pointer or arrow keys.",
  deck: "First, middle and last slide with a live slide count.",
  "dialog-stack": "First, middle and review step; Back retains app-owned input, Finish closes the modal.",
  editor: "Editable or read-only document with heading, emphasis, list and quote controls.",
  glimpse: "Native link alone, hover preview and keyboard-focus preview.",
  marquee: "Running, manually paused and paused by reduced-motion preference.",
  pill: "Neutral, success, warning or danger cue; optional removable and disabled state.",
  "qr-code": "Scannable SVG with optional copy action and copied feedback.",
  rating: "Editable selected score or read-only summary; arrows change an editable score.",
  "relative-time": "Past or future phrase with absolute timestamp semantics.",
  spinner: "Eight visual forms and three sizes; all animation stops under reduced motion.",
  status: "Neutral, success, warning or danger; optional pulse stops under reduced motion.",
  "theme-switcher": "Light or dark, controlled or self-managed selection.",
  tree: "Expanded/collapsed branch, focused/selected leaf and disabled leaf.",
};
