import type { items } from "./items";

/** States supported by the distributed source. The live preview shows a useful subset. */
export const itemStates: Record<keyof typeof items, string> = {
  "brand-logo": "Full or icon-only at three sizes, app-owned name and mark, light/dark foreground. A surrounding link supplies hover and focus behavior; disabled and loading do not apply to a static identity.",
  button: "Default, hover, focus-visible, disabled and loading; loading prevents another activation.",
  input: "Empty, filled, focused, invalid and disabled; file inputs also show the selected file control.",
  select: "Closed, open, selected, focused and disabled; arrow keys move through options.",
  switch: "Unchecked, checked, focused and disabled; Space changes the value.",
  tabs: "Selected and unselected tabs, focused tab and horizontal or vertical orientation.",
  label: "A static native label; required or invalid feedback belongs to its associated input.",
  textarea: "Empty, filled, focused, invalid and disabled.",
  badge: "Default, secondary, outline and destructive presentations; labels carry meaning beyond color.",
  card: "Default and small density; optional leading image, action and footer.",
  separator: "Horizontal or vertical; decorative by default.",
  dialog: "Closed trigger, open modal, editable content, save/cancel and Escape focus return.",
  "dropdown-menu": "Closed/open menu, highlighted item, disabled item and destructive action.",
  popover: "Closed/open anchored content and focused controls; Escape restores focus.",
  sheet: "Closed/open side panel, focused content and Escape close.",
  tooltip: "Hidden, pointer hover and keyboard focus; content is supplementary.",
  chart: "Populated series and responsive layout; empty or loading data is an application decision.",
  skeleton: "Neutral by default, optional brand variant and reduced-motion stop.",
  "brand-gradient-text": "Static or animated short text; reduced motion stops repetition.",
  "status-notice": "Neutral, success, warning and destructive feedback with matching live-region semantics.",
  "reveal-content": "Before entry, visible after entry and immediately visible under reduced motion or without script.",
  collapsible: "Collapsed and expanded content with an announced trigger state.",
  progress: "Measured value with label; use a loading indicator when progress cannot be measured.",
  slider: "Single value or two-value range, focused thumb and keyboard adjustment.",
  toast: "Idle trigger, visible message and dismissal; the application chooses the result text.",
  avatar: "Loaded image or text fallback.",
  "alert-dialog": "Closed/open confirmation, explicit cancel or destructive confirmation and focus return.",
  "avatar-stack": "Named member avatars and an overflow count when more people are present.",
  cursor: "One or several app-positioned collaborator cursors with separate presence text.",
  calendar: "Schedule or compact date view, selected day, changed month and keyboard day navigation.",
  list: "Grouped rows before and after a keyboard-available move.",
  table: "Unsorted and sorted columns; dense rows scroll within the table on narrow screens.",
  "page-header": "Stacked actions on narrow screens and a row layout when space permits.",
  "state-panel": "Neutral, success, warning or destructive message; action and heading level are optional.",
  "product-page-intro": "Index, detail or task hierarchy with optional meta and aside action.",
  "resource-row-link": "Default, hover and focus-visible row; choose one link or one button target.",
  "page-skeleton": "Busy page structure with named loading status; motion stops under reduced motion.",
  "filter-toolbar": "Pressed/unpressed filters, search query, sort choice and an app-owned result count.",
  "empty-state": "First-use or zero-result message with an optional app-owned next action.",
  "form-section": "Stacked narrow layout or two-column layout with individually labelled fields.",
  "search-field": "Empty or populated query; the application supplies matching and no-result states.",
  "stat-card": "Value and optional detail; the application owns update and loading states.",
  "settings-section": "Grouped field values and an application-owned unsaved/saved result.",
  "bento-grid": "Responsive article spans and hover/focus-within emphasis; content remains app-owned.",
  gantt: "Scheduled item, moved item and resized duration with keyboard controls.",
  kanban: "Cards in multiple columns and a moved-card result with live status.",
  "code-block": "Selected sample or plain code, optional line numbers and copied feedback.",
  "contribution-graph": "Low/high activity, selected day and a scrollable annual grid on narrow screens.",
  sandbox: "Code, preview and optional console tabs; keyboard arrows select the view.",
  snippet: "Selected command tab and copied feedback for the active value.",
  choicebox: "Selected, unselected, focused and disabled choices.",
  combobox: "Closed, open, searching, empty, selected and disabled option.",
  dropzone: "Idle, dragging, accepted file, rejected file and disabled browse.",
  "mini-calendar": "Selected day and previous/next seven-day strip.",
  tags: "Selected tags, suggestion, added/removed tag, maximum count and disabled entry.",
  "image-crop": "Visible image, adjustable crop, reset and applied percentage bounds.",
  "image-zoom": "Thumbnail trigger and focused modal image; Escape closes it.",
  "credit-card": "Masked front and back, selected by the flip control.",
  ticker: "Positive or negative change and collapsed/expanded supplied details.",
  stories: "Thumbnail triggers, open viewer, current story, play/pause and reduced-motion stop.",
  reel: "Current video, play/pause, mute and previous/next; reduced motion starts paused.",
  "video-player": "Paused/playing, seek position and muted/unmuted audio.",
  announcement: "Linked, static or dismissed compact update.",
  banner: "Prominent or subtle page message with optional dismissal.",
  typography: "Semantic element and visual type role are selected independently; text has no interactive state.",
  "color-picker": "Preset, saturation/brightness plane, hue, opacity and validated HEX entry.",
  comparison: "Before/after exposure from 0–100%, adjusted by pointer or arrow keys.",
  deck: "First, middle and last slide with a live slide count.",
  "dialog-stack": "First, middle and review step; Back retains app-owned input, Finish closes the modal.",
  editor: "Editable or read-only document with heading, emphasis, list and quote controls.",
  glimpse: "Native link alone, hover preview and keyboard-focus preview.",
  marquee: "Running, manually paused and paused by reduced-motion preference.",
  pill: "Neutral, success, warning or danger cue; optional removable and disabled state.",
  "qr-code": "Scannable SVG with optional copy action and copied feedback.",
  rating: "Editable selected score or read-only summary; arrows change an editable score.",
  "relative-time": "Past or future phrase with absolute timestamp semantics.",
  spinner: "Eight visual forms and three sizes; all animation stops under reduced motion.",
  status: "Neutral, success, warning or danger; optional pulse stops under reduced motion.",
  "theme-switcher": "Light or dark, controlled or self-managed selection.",
  tree: "Expanded/collapsed branch, focused/selected leaf and disabled leaf.",
};
